
import json
import os

# More facts for remaining animals
FACTS = {
    'common grackle': 'Grackles can mimic sounds including car alarms!',
    'european starling': 'Starlings can mimic human speech and sing complex songs!',
    'house finch': 'Male house finches get their red color from berries they eat!',
    'parakeet (feral)': 'Parakeets can learn over 100 words and live 20 years!',
    'box turtle': 'Box turtles can live over 100 years and remember where food grows!',
    "cooper's hawk": 'Coopers hawks can fly through dense forests at high speed!',
    'european robin': 'Robins can see magnetic fields to navigate!',
    'garter snake': 'Garter snakes are harmless and eat garden pests!',
    'pileated woodpecker': 'Pileated woodpeckers make holes big enough for owls to use!',
    'pine marten': 'Pine martens can catch squirrels in trees!',
    'wood frog': 'Wood frogs freeze solid in winter and thaw alive in spring!',
    'blue morpho butterfly': 'Blue morpho wings shimmer because of tiny scales, not pigment!',
    'capybara': 'Capybaras are the worlds largest rodents and love to swim!',
    'cassowary': 'Cassowaries have a helmet-like crest and powerful kicks!',
    'rhinoceros hornbill': 'Hornbills have a hollow horn that makes their calls louder!',
    'addax': 'Addax can survive months in the desert without drinking water!',
    'banded coral shrimp': 'Cleaner shrimp set up stations where fish line up for cleaning!',
    'bark scorpion': 'Bark scorpions can survive being frozen and thaw back to life!',
    'bigeye soldierfish': 'Soldierfish have huge eyes to see in the dark reef!',
    'black crappie': 'Crappies build nests and guard their eggs!',
    'black-crowned night heron': 'Night herons drop bait to lure fish!',
    'brittle star': 'Brittle stars can drop their arms to escape and regrow them!',
    'cactus wren': 'Cactus wrens build nests inside spiny cacti for protection!',
    'california spiny lobster': 'Spiny lobsters migrate in long single-file lines!',
    'camel spider': 'Camel spiders are not spiders and cannot hurt humans!',
    'cardinalfish': 'Male cardinalfish carry eggs in their mouths!',
    'cave boa': 'Cave boas catch bats flying out of caves!',
    'cave crayfish': 'Cave crayfish are white from living in darkness!',
    'cave cricket': 'Cave crickets have extra long antennae to feel in the dark!',
    'cave rat': 'Cave rats help spread seeds near cave entrances!',
    'cave salamander': 'Cave salamanders glow orange and live 20 years!',
    'cave shrimp': 'Cave shrimp are see-through and live in underground streams!',
    'cave spider': 'Cave spiders spin webs in total darkness!',
    'cave swiftlet': 'Swiftlets build nests from their own saliva!',
    'chuckwalla': 'Chuckwallas puff up in rock cracks so predators cant pull them out!',
    'clouded leopard': 'Clouded leopards can hang upside down from branches!',
    'conger eel': 'Conger eels can grow over 9 feet long!',
    'deep-sea hatchetfish': 'Hatchetfish use lights to hide their shadow from below!',
    'desert tortoise': 'Desert tortoises dig burrows to escape the heat!',
    'dromedary camel': 'Camels can drink 30 gallons of water in 13 minutes!',
    'firefly squid': 'Firefly squid light up the ocean with blue glow!',
    'freshwater crab': 'Freshwater crabs can breathe air and walk on land!',
    'freshwater shrimp': 'Freshwater shrimp keep water clean by eating algae!',
    'galago (bushbaby)': 'Bushbabies can jump 6 feet straight up!',
    'humboldt squid': 'Humboldt squid hunt in packs and flash colors to talk!',
    'hyena (denning)': 'Hyenas have the strongest bite of almost any mammal!',
    'mexican tetra (blind cave fish)': 'Cave fish lost their eyes because they dont need them!',
    'necturus (mudpuppy)': 'Mudpuppies keep their gills their whole life!',
    'northern collared lemming': 'Lemmings are one of few rodents that turn white in winter!',
    'olm (proteus)': 'Olms can live 100 years and survive 10 years without food!',
    'pacific hagfish': 'Hagfish produce buckets of slime when attacked!',
    'peccary (javelina)': 'Javelinas rub scent on each other to recognize family!',
    'short-tailed weasel': 'Weasels do a war dance to confuse their prey!',
    'spectacled caiman': 'Caimans are related to alligators!',
    'spectacled eider': 'Spectacled eiders have white goggle markings!',
    'spider (house)': 'House spiders help by eating flies and mosquitoes!',
    'arctic tern': 'Arctic terns fly from pole to pole, the longest migration ever!',
    'atlantic puffin': 'Puffins can hold over 10 fish in their beak at once!',
    'dall sheep': 'Dall sheep climb steep cliffs to escape predators!',
    'ermine (stoat)': 'Ermines turn white in winter except for their black tail!',
    'aggregate anemone': 'Anemones clone themselves by splitting in half!',
    'arapaima': 'Arapaima are giant fish that breathe air!',
    'brown trout': 'Brown trout can jump 6 feet over waterfalls!',
    'chiton': 'Chitons have eyes made of actual rock crystals!',
    'common limpet': 'Limpets have the strongest teeth of any animal!',
    'gooseneck barnacle': 'Gooseneck barnacles travel the world attached to ships!',
    'largemouth bass': 'Bass can eat prey almost as big as themselves!',
    'ochre sea star': 'Sea stars can regrow arms and even whole bodies!',
    'periwinkle snail': 'Periwinkles close their shell door to survive low tide!',
    'sally lightfoot crab': 'Sally Lightfoot crabs can run across water!',
    'sea palm': 'Sea palms are seaweed that survive crashing waves!',
    'tidepool sculpin': 'Sculpins can breathe air when trapped in tide pools!',
    'garden eel': 'Garden eels live in colonies poking out of the sand!',
    'great barracuda': 'Barracudas can swim up to 35 miles per hour!',
    'humphead wrasse': 'Humphead wrasse can live over 30 years!',
    'loggerhead turtle': 'Loggerheads have powerful jaws to crush shellfish!',
    'barreleye fish': 'Barreleye fish have see-through heads!',
    'giant isopod': 'Giant isopods can go 5 years without eating!',
    'pacific viperfish': 'Viperfish have fangs so big they cant close their mouth!',
    'american alligator': 'Alligators have been around since the time of dinosaurs!',
    'american black bear': 'Black bears can smell food from 5 miles away!',
    'atlantic bottlenose dolphin': 'Dolphins sleep with one eye open!',
    'boreal owl': 'Boreal owls can hear a vole moving under 2 feet of snow!',
    'bristlemouth': 'Bristlemouths are the most numerous fish in the ocean!',
    'common octopus': 'Octopuses can change color in less than a second!',
    'cookiecutter shark': 'Cookiecutter sharks take round bites out of larger fish!',
    'crabeater seal': 'Crabeater seals dont actually eat crabs - they eat krill!',
    'deep sea prawn': 'Deep sea prawns can spit glowing liquid to confuse predators!',
    'desert hedgehog': 'Desert hedgehogs can eat scorpions without getting stung!',
    'dragonfly': 'Dragonflies can fly in any direction, even backwards!',
    'dugong': 'Dugongs are the only sea mammals that eat only plants!',
    'eel': 'Eels can travel over land when it rains!',
    'egret': 'Egrets grow beautiful feathers called plumes during mating season!',
    'electric eel': 'Electric eels can produce 600 volts of electricity!',
    'elephant seal': 'Elephant seals can hold their breath for 2 hours!',
    'elf owl': 'Elf owls are the smallest owls and live in cactus holes!',
    'emperor scorpion': 'Emperor scorpions glow bright blue under UV light!',
    'feral cat': 'Feral cats can survive in the wild by hunting small animals!',
    'fiddler crab': 'Male fiddler crabs wave their big claw to attract females!',
    'fire ant': 'Fire ants link together to form rafts that float on floods!',
    'flamingo': 'Flamingos are pink because of the shrimp they eat!',
    'flashlight fish': 'Flashlight fish have glowing organs under their eyes!',
    'flying squirrel': 'Flying squirrels can glide over 150 feet between trees!',
    'freshwater dolphin': 'River dolphins are pink and use echolocation!',
    'frilled shark': 'Frilled sharks look like sea serpents and have 300 teeth!',
    'fruit bat': 'Fruit bats can see in color and find food by smell!',
    'garden snail': 'Garden snails have thousands of tiny teeth on their tongue!',
    'gar': 'Gars have been around since dinosaurs roamed the earth!',
    'gecko': 'Geckos can walk on ceilings using millions of tiny hairs on their feet!',
    'ghost crab': 'Ghost crabs can run sideways at 10 miles per hour!',
    'giant salamander': 'Giant salamanders can grow over 5 feet long!',
    'gila monster': 'Gila monsters are one of the only venomous lizards in the world!',
    'glowworm': 'Glowworms light up cave ceilings like tiny stars!',
    'goblin shark': 'Goblin sharks can shoot their jaws forward to catch prey!',
    'great blue heron': 'Great blue herons swallow fish whole, headfirst!',
    'green frog': 'Green frogs make a sound like plucking a banjo string!',
    'green sea turtle': 'Sea turtles can hold their breath for over 5 hours!',
    'greenland shark': 'Greenland sharks can live over 400 years!',
    'gulper eel': 'Gulper eels can swallow fish bigger than themselves!',
    'harvestman': 'Harvestmen are not spiders even though they look like them!',
    'hatchetfish': 'Hatchetfish have bodies shaped like tiny axes!',
    'hellbender salamander': 'Hellbenders breathe through their wrinkly skin!',
    'hermit crab': 'Hermit crabs line up by size to trade shells!',
    'honey bee': 'Bees dance to tell other bees where to find flowers!',
    'horned lizard': 'Horned lizards can squirt blood from their eyes!',
    'horseshoe crab': 'Horseshoe crabs have blue blood that helps make medicine!',
    'house mouse': 'Mice can squeeze through holes as small as a dime!',
    'house sparrow': 'House sparrows take dust baths to keep clean!',
    'hyena': 'Hyenas have one of the strongest bites of any mammal!',
    'japanese spider crab': 'Japanese spider crabs have legs that span 12 feet!',
    'jellyfish': 'Jellyfish are 95% water and have no brain or heart!',
    'jerboa': 'Jerboas can jump over 6 feet high on their tiny legs!',
    'kangaroo rat': 'Kangaroo rats never need to drink water!',
    'kingfisher': 'Kingfishers dive into water at 25 mph to catch fish!',
    'kinkajou': 'Kinkajous have a 5-inch tongue to reach nectar!',
    'kit fox': 'Kit foxes have huge ears to hear prey underground!',
    'koi': 'Koi fish can live over 200 years!',
    'krill': 'Krill are tiny but together weigh more than all humans!',
    'lanternfish': 'Lanternfish make the biggest animal migration every day!',
    'lemming': 'Lemmings dig tunnels under the snow to stay warm!',
    'leopard seal': 'Leopard seals are top predators in Antarctica!',
    'lionfish': 'Lionfish have venomous spines but are beautiful!',
    'little brown bat': 'Little brown bats can eat 1000 mosquitoes in one hour!',
    'lobster': 'Lobsters taste with their feet!',
    'luna moth': 'Luna moths have no mouth and only live for a week!',
    'lynx': 'Lynx have huge paws that work like snowshoes!',
    'magpie': 'Magpies can recognize themselves in a mirror!',
    'mallard duck': 'Mallard ducks sleep with one eye open!',
    'manta ray': 'Manta rays have the largest brain of any fish!',
    'mantis shrimp': 'Mantis shrimp punch fast enough to boil water!',
    'margay': 'Margays can mimic baby monkeys to lure prey!',
    'marine iguana': 'Marine iguanas sneeze out salt from ocean water!',
    'marsh rabbit': 'Marsh rabbits are excellent swimmers!',
    'meerkat': 'Meerkats take turns standing guard!',
    'mexican free-tailed bat': 'These bats fly higher than any other bat!',
    'millipede': 'Millipedes curl into a ball when scared!',
    'mink': 'Minks can swim underwater to catch fish!',
    'monarch butterfly': 'Monarch butterflies travel 3000 miles every year!',
    'monitor lizard': 'Monitor lizards have forked tongues like snakes!',
    'moray eel': 'Moray eels have a second set of jaws in their throat!',
    'moth': 'Moths can hear sounds humans cannot!',
    'mudskipper': 'Mudskippers are fish that can walk on land!',
    'musk ox': 'Musk ox wool is 8 times warmer than sheep wool!',
    'muskrat': 'Muskrats can hold their breath for 20 minutes!',
    'narwhal': 'The narwhal tusk is a tooth that grows 10 feet long!',
    'newt': 'Newts can regrow lost limbs and eyes!',
    'nile crocodile': 'Nile crocodiles can go a year without eating!',
    'nudibranch': 'Nudibranchs come in every color of the rainbow!',
    'nutria': 'Nutrias have orange teeth from iron in their enamel!',
    'oarfish': 'Oarfish can grow 36 feet long!',
    'oilbird': 'Oilbirds use echolocation like bats!',
    'ostrich': 'Ostrich eyes are bigger than their brains!',
    'otter': 'Otters hold hands while sleeping!',
    'owl': 'Owls can turn their heads almost all the way around!',
    'painted turtle': 'Painted turtles survive being frozen solid!',
    'peacock': 'Only male peacocks have the colorful tail feathers!',
    'pelican': 'A pelicans pouch can hold 3 gallons of water!',
    'peregrine falcon': 'Peregrine falcons dive at 240 mph!',
    'piranha': 'Piranhas bark like dogs to scare predators!',
    'platypus': 'Platypuses lay eggs like reptiles!',
    'porcupine': 'Porcupines have 30,000 sharp quills!',
    'possum': 'Possums play dead to trick predators!',
    'prairie dog': 'Prairie dogs have a complex language!',
    'praying mantis': 'Praying mantises can turn their heads 180 degrees!',
    'pronghorn': 'Pronghorns are the second fastest land animal!',
    'pseudoscorpion': 'Pseudoscorpions catch rides on beetles!',
    'ptarmigan': 'Ptarmigans turn white in winter!',
    'purple sea urchin': 'Sea urchins eat kelp forests!',
    'raccoon': 'Raccoons have super sensitive hands!',
    'raven': 'Ravens can solve puzzles and play tricks!',
    'red fox': 'Red foxes hear watches ticking from 40 yards away!',
    'red kangaroo': 'Red kangaroos jump 25 feet in one leap!',
    'red-tailed hawk': 'Red-tailed hawk screams are used in movies for eagles!',
    'red-winged blackbird': 'Blackbirds attack much larger birds to defend nests!',
    'reef shark': 'Reef sharks patrol the same reef their whole lives!',
    'river otter': 'River otters slide on mud for fun!',
    'roadrunner': 'Roadrunners can run 20 mph!',
    'rock pigeon': 'Pigeons carried messages in wars!',
    'roseate spoonbill': 'Spoonbills swing their bills to catch food!',
    'salamander': 'Salamanders breathe through their skin!',
    'sand cat': 'Sand cats survive without drinking water!',
    'sandhopper': 'Sandhoppers jump 100 times their body length!',
    'scorpion': 'Scorpions glow blue under UV light!',
    'sea cucumber': 'Sea cucumbers breathe through their butt!',
    'sea lettuce': 'Sea lettuce is a green seaweed!',
    'seagull': 'Seagulls can drink salt water!',
    'seahorse': 'Seahorse dads carry the babies!',
    'shoebill stork': 'Shoebills look like dinosaurs!',
    'shore crab': 'Shore crabs can regrow lost claws!',
    'sidewinder rattlesnake': 'Sidewinders move sideways over hot sand!',
    'six-gill shark': 'Six-gill sharks are living fossils!',
    'skunk': 'Skunk spray can be smelled a mile away!',
    'slow loris': 'Slow lorises are venomous!',
    'snail': 'Snails can sleep for 3 years!',
    'snipe eel': 'Snipe eels have curved jaws like a beak!',
    'snowy owl': 'Snowy owls hunt during the day!',
    'spanish dancer': 'Spanish dancers swim like a flamenco dress!',
    'spider': 'Spiders eat their own webs to recycle them!',
    'spotted eagle ray': 'Eagle rays jump out of the water!',
    'springtail': 'Springtails have a tail that launches them into the air!',
    'squirrel': 'Squirrels plant trees by forgetting nuts!',
    'squirrelfish': 'Squirrelfish make grunting sounds!',
    'starfish': 'Starfish pump water through their body instead of blood!',
    'stingray': 'Stingrays hide in the sand!',
    'stoplight loosejaw': 'Loosejaws have a jaw that swings open wide!',
    'striped skunk': 'Striped skunks warn enemies by stomping!',
    'sturgeon': 'Sturgeons look like armored dinosaurs!',
    'sugar glider': 'Sugar gliders have a built-in parachute!',
    'swan': 'Swans are very protective parents!',
    'tarantula hawk': 'Tarantula hawks hunt tarantulas!',
    'tarsier': 'Tarsiers have huge eyes for night vision!',
    'thorny devil': 'Thorny devils drink with their skin!',
    'toucan': 'Toucans toss fruit in the air to eat it!',
    'tree kangaroo': 'Tree kangaroos live in trees instead of on the ground!',
    'tripod fish': 'Tripod fish stand on their fins!',
    'trumpetfish': 'Trumpetfish suck up prey like a vacuum!',
    'vampire bat': 'Vampire bats run on the ground!',
    'vampire squid': 'Vampire squids turn inside out when scared!',
    'viperfish': 'Viperfish have glowing lights on their belly!',
    'virginia opossum': 'Opossums have a pouch like kangaroos!',
    'vulture': 'Vultures keep the world clean by eating dead things!',
    'walleye': 'Walleyes have glowing eyes!',
    'water buffalo': 'Water buffaloes love mud baths!',
    'water moccasin': 'Water moccasins swim with their head up!',
    'water shrew': 'Water shrews run on water!',
    'weasel': 'Weasels are fearless hunters!',
    'weddell seal': 'Weddell seals sing loud songs underwater!',
    'whip-poor-will': 'Whip-poor-wills say their own name!',
    'wild boar': 'Wild boars are great swimmers!',
    'wild turkey': 'Wild turkeys sleep in trees!',
    'wolf': 'Wolves have family packs!',
    'wolverine': 'Wolverines are strong enough to climb mountains!',
    'woodpecker': 'Woodpeckers wrap their tongue around their brain!',
}

animals_path = os.path.join(os.path.dirname(__file__), '..', 'animals_fixed.json')

with open(animals_path, 'r', encoding='utf-8') as f:
    animals = json.load(f)

updated = 0
for a in animals:
    key = a['name'].lower()
    if 'amazing animal' in a.get('fact', '').lower() and key in FACTS:
        a['fact'] = FACTS[key]
        updated += 1

with open(animals_path, 'w', encoding='utf-8') as f:
    json.dump(animals, f, indent=2, ensure_ascii=False)

remaining = [a['name'] for a in animals if 'amazing animal' in a.get('fact','').lower()]
print(f'Updated {updated} animals')
print(f'Remaining: {len(remaining)}')
if remaining:
    print(remaining)
else:
    print('ALL DONE!')
